Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/RescueModifier:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Layout/LineLength:
  Enabled: false
Metrics/AbcSize:  
  Enabled: false